spring:
  config:
    import:
      - optional:classpath:application-secret.yml
      - optional:file:./config/application-secret.yml

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-name: Github
            scope: ["read:user", "user:email"]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8080

frontend:
  url: ${FRONTEND_URL}